#!/bin/bash

# wrapper around python program since coding task spec states the
#  program should be invoked without .py extension (ie ./most_active_cookie )



# Check the number of command-line arguments
if (("$#" < 3)); then
    echo "Usage: most_active_cookie <cookie_log_file_path.csv> -d <YYYY-MM-DD_date>"
    exit 1
fi
python3 most_active_cookie.py $1 $3  # $2 == "-d"
