#!/bin/bash

# wrapper around python program since coding task spec states the
#  program should be invoked without .py extension (ie ./most_active_cookie )



# Check the number of command-line arguments
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <arg1> <arg2> ..."
    exit 1
fi
python3 most_active_cookie.py $1 $3 # $2 == -d
